[package]
name = "sally-mc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
nalgebra = "0.32.5"
num-traits = "0.2.18"
serde_json = "1.0"